# Action to build, test and publish the Docker image
# Uploading to Docker Hub only happens on changes to master
name: default

on:
  # Enable option to manually run the action:
  workflow_dispatch:

  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  main:
    name: Build and test image
    runs-on: ubuntu-latest
    if: github.repository == 'dlang-tour/core-dreg'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login to DockerHub to push the generated image after the build
      - name: Login to DockerHub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          tags: dlangtour/core-dreg:latest
          context: .

      - name: Verify the image
        run: ./test.sh "dlangtour/core-dreg:latest"

      - name: Push image
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name == 'push' }}
          tags: dlangtour/core-dreg:latest
          context: .
