name: default

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  main:
    name: Build and test image

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name == 'push' }}
          load: ${{ github.event_name != 'push' }}
          tags: dlangtour/core-dreg:latest

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Run test.sh
        run: ./test.sh "dlangtour/core-dreg:latest"

    runs-on: ubuntu-latest
